libsecril-client: Move to vendor
Resolves:
error: "audio.primary.exynos7870 (native:vendor) can not link against libsecril-client (native:platform)"

Change-Id: I80a5a4759dfa9b88af0a9fe1115755b3a0677d28